source "https://rubygems.org"

# Specify minimum Ruby version (3.2.0 or higher)
ruby ">= 3.2.0"

# Jekyll and plugins
gem "jekyll", "~> 4.3.2"
gem "just-the-docs", "~> 0.7.0"

# Jekyll plugins
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.15"
  gem "jekyll-sitemap", "~> 1.4"
end

# Fix for protobuf compatibility issues
gem "google-protobuf", "~> 3.25.0"

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :windows, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:windows]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]